### ISSUE TITLE
Length of `video_idx` not matching with the length of the other lists

### ISSUE THREAD

**Issue by shan18** [OpenDriveLab/PPGeo#1]
Hi, I was going through the data processing script and had a question regarding the lengths of the lists being created.

In these lines, we see that the length of the lists being created is equal to `len(tmp_path) - 4`
https://github.com/OpenDriveLab/PPGeo/blob/e720ae590054eb1254175d6eb44e692183518345/ytb_data_preprocess.py#L31-L33

But here the `len(video_idx)` is equal to `len(tmp_path)`
https://github.com/OpenDriveLab/PPGeo/blob/e720ae590054eb1254175d6eb44e692183518345/ytb_data_preprocess.py#L36

Wouldn't this create a mismatch between some of the frames and their corresponding video indexes here?
https://github.com/OpenDriveLab/PPGeo/blob/e720ae590054eb1254175d6eb44e692183518345/ytb_data_preprocess.py#L38

**Comment by penghao-wu** [comment]
There were some bugs in the previous ytb_data_preprocess.py. It should be fixed now.

**Comment by shan18** [comment]
Thanks a lot for fixing the bugs. I just have 2 more questions about the script.

1. Is there a reason as to why we skip the first 3 frames
  https://github.com/OpenDriveLab/PPGeo/blob/345ba9714cbc66636be11b94910981ea7ec1ddc2/ytb_data_preprocess.py#L27

2. Similary, why is the 65th folder being skipped?
  https://github.com/OpenDriveLab/PPGeo/blob/345ba9714cbc66636be11b94910981ea7ec1ddc2/ytb_data_preprocess.py#L16

**Comment by penghao-wu** [comment]
I found that the first few frames are just black in some clips so I skip them. 
It seems that the image index in the 65th folder is not correct so I skip it.

**Comment by shan18** [comment]
Got it. Thanks a lot for the response.
