### ISSUE TITLE
Collision Rate and L2 for nuScenes Planning

### ISSUE THREAD

**Issue by shan18** [OpenDriveLab/PPGeo#2]
Hi, I had two questions regarding the `nuScenes Planning` task:

1. The results mentioned in the paper (Table 2), after how many epochs did you train the model to get those scores?
2. The table also shows a `Collision Rate (%)` metric which seems to be missing from the code in the repository. Will it be possible for you to share how the collision rate was calculated?

**Comment by penghao-wu** [comment]
1. We train the model for 20 epochs and use the result of the saved best model.
2. We use the script in ST-P3 https://github.com/OpenPerceptionX/ST-P3/blob/main/evaluate.py for collision rate calculation.

**Comment by shan18** [comment]
I see that the checkpoints obtained from the `train_planning.py` [script](https://github.com/OpenDriveLab/PPGeo/blob/main/nuscenes_planning/train_planning.py) given in this repo are incompatible with the `evaluate.py` script you mentioned for calculating the collision rate. 

Did you make any modifications to the `St-P3` codebase to make it compatible with the checkpoints obtained from this repository?

**Comment by penghao-wu** [comment]
We modify the ST-P3 evaluate.py to remove unrelated task evaluations like perception tasks and only do the collision rate calculation. The collision rate calculation process is not modified.

**Comment by shan18** [comment]
Got it. Thanks a lot
