### ISSUE TITLE
Dataset sampling for Town05-long (TCP) downstream task

### ISSUE THREAD

**Issue by macandro96** [OpenDriveLab/PPGeo#3]
Hi,
I had a couple questions on the training data and simulation evaluation for the `TCP` downstream task. 

1.  In the [TCP paper](https://arxiv.org/pdf/2206.08129.pdf), it is mentioned that the dataset size for ablations are 189k and for the leaderboard submission it's 420k. But for PPGeo Town05-long downstream evaluation task, 40k samples are used for training. I was wondering what's strategy for down-sampling 40k from 189k? Also, it would be great if you could release the scripts for those as well. 

2. For the evaluation part, are there any scripts for eg. in the [TCP repo](https://github.com/OpenPerceptionX/TCP), that can be used to fetch the Driving score, infraction score, route completion, collisions pedestrians, etc.?

**Comment by penghao-wu** [comment]
1. We simply do the down-sampling like ```self.front_img = self.front_img[::4][:40000]``` in the ```CARLA_Data``` Dataset.
2. You can use this [script](https://github.com/OpenPerceptionX/TCP/blob/main/tools/statistics.py) to get the statistics.
3. Also note that we set the alpha value to 0.5 in the TCP agent for evaluation (so you need to modify https://github.com/OpenPerceptionX/TCP/blob/9dcecad76cb10ae1c7f79c9f71c517b29c3bf614/leaderboard/team_code/tcp_agent.py#L214 and https://github.com/OpenPerceptionX/TCP/blob/9dcecad76cb10ae1c7f79c9f71c517b29c3bf614/leaderboard/team_code/tcp_agent.py#L220)

**Comment by macandro96** [comment]
Thank you so much for the response. This helps. Just a couple more follow-up questions.

1. Is there any hyperparameter tuning required to fine-tune the model or do we use the default hyperparameters?
2. To get similar results on the paper, do we evaluate on Town05-long by running `sh leaderboard/scripts/run_evaluation.sh` with `ROUTES=leaderboard/data/evaluation_routes/routes_town05_long.xml` and then running the `tools/statistics.py` script?

**Comment by penghao-wu** [comment]
1. We use the default hyperparameters.
2. Yes

**Comment by macandro96** [comment]
Got it. For the model part - to replicate the results for this downstream tasks, do we just - 

1. Insert the line `self.front_img = self.front_img[::4][:40000]` at the end of the `__init__()` in the `Carla_Data` dataset
2. Load the PPGeo `state_dict` in the `self.perception` module  in `model.py` i.e
```
self.perception = resnet34(pretrained=True)
path_to_ckpt_file ='path/to/resnet34.ckpt'

ckpt = torch.load(path_to_ckpt_file, map_location='cpu')

ckpt = ckpt["state_dict"]
new_state_dict = OrderedDict()
for key, value in ckpt.items():
        new_key = key.replace("motionnet.visual_encoder.encoder.","")
        new_state_dict[new_key] = value

self.perception.load_state_dict(new_state_dict, strict = False)
```

Is there anything else, that we need to change in the TCP scripts to reproduce the results?

Appreciate your response.

Thank you for all the help!

**Comment by penghao-wu** [comment]
1. Besides the front_img, other quantities should also be sampled like
```
self.front_img = self.front_img[::4][:40000]
self.x = self.x[::4][:40000]
self.y = self.y[::4][:40000]
self.command = self.command[::4][:40000]
self.theta = self.theta[::4][:40000]
self.speed = self.speed[::4][:40000]


self.value = self.value[::4][:40000]
self.feature = self.feature[::4][:40000]
self.action = self.action[::4][:40000]
self.action_mu = self.action_mu[::4][:40000]
self.action_sigma = self.action_sigma[::4][:40000]


self.x_command = self.x_command[::4][:40000]
self.y_command = self.y_command[::4][:40000]
self.only_ap_brake = self.only_ap_brake[::4][:40000]


self.future_x = self.future_x[::4][:40000]
self.future_y = self.future_y[::4][:40000]
self.future_theta = self.future_theta[::4][:40000]

self.future_feature = self.future_feature[::4][:40000]
self.future_action = self.future_action[::4][:40000]
self.future_action_mu = self.future_action_mu[::4][:40000]
self.future_action_sigma = self.future_action_sigma[::4][:40000]
self.future_only_ap_brake = self.future_only_ap_brake[::4][:40000]
```
2. Due to the refactoring of the TCP codebase and this one, the scenario file used and some details might be different. I re-run the experiment using the public codebases. 
Now the expected result for PPGeo pre-trained TCP should be
![2VFw8rAuK7](https://user-images.githubusercontent.com/62696862/221097953-e91f30b7-1092-48a1-b2b0-5d56e3510216.png)
And the expected result for ImageNet pre-trained TCP should be
![2DcJeCiycF](https://user-images.githubusercontent.com/62696862/221098064-4d239753-654d-4258-895d-4aab4ef43bf2.png)

**Comment by macandro96** [comment]
Got it. Thank you so much.
