### ISSUE TITLE
Training of the fc layer in resnet34 visual encoder

### ISSUE THREAD

**Issue by macandro96** [OpenDriveLab/PPGeo#4]
I was wondering is the fully connected layer in the visual encoder model being trained or is it frozen? Because the weight of the fully connected layer in the given checkpoint and the pretrained imagenet resnet34 encoder exactly matches.

```
import torch
from torchvision.models import resnet34

resnet_imagenet = resnet34(pretrained=True)
ppgeo_ckpt = torch.load('resnet34.ckpt')['state_dict']

torch.all(ppgeo_ckpt['fc.weight'] == resnet_imagenet.fc.weight)  # returns True
```

Thanks!

**Comment by penghao-wu** [comment]
The fully connected layer in the visual encoder is not used or trained in our model.
